version: '3.9'

#Docker Networks
networks:
    leather_club:
        driver: bridge
    postgres:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
    pgadmin:
        driver: local

# Workflow
services:
    base_app: &base_app
        build:
            context: .
            dockerfile: ./docker/swoole/dockerfile
            args:
                APP_UID: ${APP_UID}
                APP_GID: ${APP_GID}
        user: "${APP_UID}:${APP_GID}"
        volumes:
            - type: bind
              source: .
              target: /var/www/html
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - leather_club

    web:
        <<: *base_app
        command: php artisan swoole:http start
        ports:
            - "1215:1215"
        healthcheck:
            test: [ 'CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:8082/health?plugin=http&plugin=rpc' ]
            interval: 2s
            timeout: 2s

    main_queue:
        <<: *base_app
        command: php artisan queue:work

    cron:
        <<: *base_app
        command: supercronic /etc/supercronic/laravel

    composer:
        build:
            context: .
            dockerfile: ./docker/composer/dockerfile
            args:
                APP_UID: ${APP_UID}
                APP_GID: ${APP_GID}
        user: "${APP_UID}:${APP_GID}"
        volumes:
            - type: bind
              source: .
              target: /var/www/html

    db:
        image: postgres:15.2
        environment:
            POSTGRES_DB: "test"
            POSTGRES_USER: "test"
            POSTGRES_PASSWORD: "test"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - type: bind
              source: ./docker/postgre/init
              target: /docker-entrypoint-initdb.d
            - type: volume
              source: dbdata
              target: /var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U test -d test" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
        networks:
            - leather_club
            - postgres
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 4G

    pgadmin:
        image: dpage/pgadmin4:5.7
        environment:
            PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "test"
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
            - type: volume
              source: pgadmin
              target: /var/lib/pgadmin
        ports:
            - "5052:80"
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 1G
        networks:
            - postgres

#    redis:
#        image: "redis:alpine"
#        container_name: redis
#        restart: unless-stopped
#        ports:
#            - "6379:6379"
#        networks:
#            - swnet
