FROM phpswoole/swoole:5.0

RUN echo -e "\nopcache.enable=1\nopcache.enable_cli=1\nopcache.jit_buffer_size=32M\nopcache.jit=1235\n" >> \
    ${PHP_INI_DIR}/conf.d/docker-php-ext-opcache.ini
#RUN groupadd -g 1000 www
#RUN useradd -u 1000 -ms /bin/bash -g www www
#    && chown -R appuser:appuser /var/www

#USER www

WORKDIR /var/www

