FROM php:8.1-fpm-alpine
ARG APP_UID
ARG APP_GID

# Work in the specific space
WORKDIR /var/www/html


# Install dependencies
RUN apk add --no-cache freetype libpng libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg

RUN NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
    docker-php-ext-install -j${NPROC} gd

RUN apk del --no-cache freetype-dev libpng-dev libjpeg-turbo-dev

# Install extensions
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
RUN install-php-extensions gd curl json mbstring pdo_pgsql xml zip bcmath iconv


RUN apk add --no-cache libstdc++ nano unzip ${PHPIZE_DEPS} \
    && pecl install swoole \
    && docker-php-ext-enable swoole \
    && apk del ${PHPIZE_DEPS}

RUN wget -O /usr/local/bin/dumb-init "https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64" \
    && wget -O /usr/bin/supercronic "https://github.com/aptible/supercronic/releases/download/v0.2.23/supercronic-linux-amd64"
RUN chmod +x /usr/local/bin/dumb-init \
    && chmod +x /usr/bin/supercronic \
    && mkdir /etc/supercronic \
    && echo '*/1 * * * * php /var/www/html/artisan schedule:run' > /etc/supercronic/laravel \
    && chown -R ${APP_UID}:${APP_GID} /var/www/html

ENTRYPOINT ["/usr/local/bin/dumb-init"]
